name: Docker Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update source
      run: |
        bash impish.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update ubuntu base
        commit_options: '--no-verify --signoff'
        repository: .
        commit_user_name: nadinsylaa
        commit_user_email: asepmlnaaa@gmail.com
        commit_author: nadinsylaa <asepmlnaaa@gmail.com>
    - name: Build and Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gengkapak/impish
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
